package com.ydgk.ssm.mappers;

import com.ydgk.ssm.entities.Infomation;
import com.ydgk.ssm.entities.InfomationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfomationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    int countByExample(InfomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    int deleteByExample(InfomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    int deleteByPrimaryKey(Integer nid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    int insert(Infomation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    int insertSelective(Infomation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    List<Infomation> selectByExample(InfomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    Infomation selectByPrimaryKey(Integer nid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") Infomation record, @Param("example") InfomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    int updateByExample(@Param("record") Infomation record, @Param("example") InfomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    int updateByPrimaryKeySelective(Infomation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infomation
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    int updateByPrimaryKey(Infomation record);
}