package com.ydgk.ssm.entities;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cid
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.coursename
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    private String coursename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseclass
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    private String courseclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.tid
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cid
     *
     * @return the value of course.cid
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cid
     *
     * @param cid the value for course.cid
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.coursename
     *
     * @return the value of course.coursename
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.coursename
     *
     * @param coursename the value for course.coursename
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseclass
     *
     * @return the value of course.courseclass
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    public String getCourseclass() {
        return courseclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseclass
     *
     * @param courseclass the value for course.courseclass
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    public void setCourseclass(String courseclass) {
        this.courseclass = courseclass == null ? null : courseclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.tid
     *
     * @return the value of course.tid
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.tid
     *
     * @param tid the value for course.tid
     *
     * @mbggenerated Fri Feb 14 20:05:07 CST 2020
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}