package com.ydgk.ssm.entities;

import java.util.Date;

public class Infomation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infomation.nid
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    private Integer nid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infomation.text
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infomation.time
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infomation.nid
     *
     * @return the value of infomation.nid
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infomation.nid
     *
     * @param nid the value for infomation.nid
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infomation.text
     *
     * @return the value of infomation.text
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infomation.text
     *
     * @param text the value for infomation.text
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infomation.time
     *
     * @return the value of infomation.time
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infomation.time
     *
     * @param time the value for infomation.time
     *
     * @mbggenerated Thu Feb 13 15:08:23 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}